services:
  nginx:
    image: nginx:stable-alpine3.21
    container_name: astro-nginx
    restart: unless-stopped
    volumes:
      - ../dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ortega-net

networks:
  ortega-net:
    external: true